config/routes.rb
Rails.application.routes.draw do

  resources :decks do
     resources :cards do
       get :flop
       post :flop
       get :back
       post :back
     end
     resources :study, only: [:index, :show]
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :deck
  validates_presence_of :question,
                        :answer

end

app/models/deck.rb
class Deck < ApplicationRecord

  has_many :cards
  validates_presence_of :title
end

app/models/gif.rb
class Gif
  attr_reader :id, :word, :url

  def initialize(parsed_data, word)
    @id = rand(0..999)
    @gif_data = parsed_data
    @url = giphy_url
    @word = word
  end

  def giphy_url
    @gif_data[:data][0][:url]
  end
end

app/models/image.rb
class Image
  attr_reader :id, :flickr_url

  def initialize(data)
    @id = rand(0..999)
    @flickr_url = farm_url(data)
  end

  def farm_url(data)
    the = data[:photos][:photo][0]
    farm = the[:farm]
    server = the[:server]
    id = the[:id]
    secret = the[:secret]
    "https://farm#{farm}.staticflickr.com/#{server}/#{id}_#{secret}.jpg"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    if params[:deck_id].nil?
      @cards = Card.all
    else
      @deck = Deck.find(params[:deck_id])
      @items = @deck.cards
    end
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @deck = Deck.find(params[:deck_id])
  end

  def create
    @deck = Deck.find(params[:deck_id])
    # @card = @deck.cards.last.id + 1
    @deck.cards.create(card_params)

    redirect_to deck_path(@deck.id)
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    @card.update(card_params)

    redirect_to deck_card_path(params[:deck_id], @card)
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to deck_cards_path(params[:deck_id])
  end


  def flop
    @card = Card.find(params[:card_id])
    @card.correct = true
    @card.save
    redirect_to deck_study_index_path(params[:deck_id])
  end

  def back
    @card = Card.find(params[:card_id])
    @card.correct = false
    @card.save
    redirect_to deck_study_index_path(params[:deck_id])
  end

  private

  def card_params
    params.permit(:question, :answer, :deck_id)
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

  def index
    @decks = Deck.all
  end

  def show
    @deck = Deck.find(params[:id])
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.create(deck_params)
    if @deck.save
      redirect_to deck_path(@deck.id)
    else
      redirect_to new_deck_path, alert: "Something went wrong. Please try agian"
    end
  end

  def edit
    @deck = Deck.find(params[:id])
  end

  def update
    @deck = Deck.find(params[:id])
    @deck.update(deck_params)

    redirect_to deck_path(@deck)
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy
    redirect_to decks_path
  end

  private

  def deck_params
    params.permit(:title, :description)
  end

end

app/controllers/end_controller.rb
# class EndController < ApplicationController
#
#   def index
#     @deck = Deck.find(params[:deck_id])
#     @cards = @deck.cards
#     @correct_count = @cards.where(correct: true).count
#     @incorrect_count = @deck.incorrect_count
#
#     one_hundred = ['congratulations', 'you rock', 'totally awesome', 'hell yes', "rock `n roll", 'kick ass']
#     point_75 = ['not bad', 'just missed it', 'almost']
#     point_50 = ['pick it up a notch', 'sorry, try again', 'you loose']
#     @congratz = one_hundred.shuffle.first
#     @you_done_well = point_75.shuffle.first
#     @try_again = point_50.shuffle.first
#
#   end
# end

app/controllers/study_controller.rb
class StudyController < ApplicationController

  def index
    @deck = Deck.find(params[:deck_id])
    @cards = @deck.cards
    correct_cards = []
    @correct_count = 0
    @incorrect_cards = []
    @incorrect_count = 0

    @cards.each do |card|
      if card.correct == nil
        @incorrect_cards << card
      elsif card.correct == false
        @incorrect_cards << card
        @incorrect_count += 1
      else
        correct_cards << card
        @correct_count +=1
      end
    end

    if @correct_count == @cards.length
        @cards.each do |card|
          card.correct = nil
          card.save
        end
      redirect_to decks_path
    else
      @current_card = @incorrect_cards.shuffle.first
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/edit.html.erb
<%= form_tag("/decks/#{params[:deck_id]}/cards/#{@card.id}", method: :patch) do %>

<%= label_tag :question, 'Question' %>
<%= text_field_tag :question, @card.question %>
<%= label_tag :answer, 'Answer' %>
<%= text_field_tag :answer, @card.answer %>

<%= submit_tag 'Update Card'%>
<% end %>

app/views/cards/index.html.erb
<div class="main">
  <div class="title">
    <h1><%= "All #{@deck.title} Cards" %></h1>
    <%= link_to 'Add a Card', new_deck_card_path(params[:deck_id]) %>
    <%= link_to 'Back to Decks', decks_path %>
  </div>

  <div class="row">
    <% @deck.cards.each_with_index do |card, index| %>
      <div class="flip-card">
        <div class="flip-card-inner">
          <div class="flip-card-front" style="background-image: url(<%= FlikrFacade.new(card.answer).word_image.flickr_url %>); background-size: 800px 800px;">
            <p class='count'> <%= "#{index +1}/#{@deck.cards.length}" %> </p>
            <div class="card-text">
              <h1> <%= card.question %> </h1>
            </div>
          </div>
          <div class="flip-card-back" style="background-image: url(<%= FlikrFacade.new(card.answer).word_image.flickr_url %>); background-size: contain;">
            <p class='count'> <%= "#{index +1}/#{@deck.cards.length}" %> </p>
            <div class="card-text">
              <h1> <%= card.answer %> </h1>
            </div>
            <%= link_to "edit", edit_deck_card_path(params[:deck_id], card.id) %>
            <%= link_to "delete", deck_card_path(params[:deck_id], card.id), :method => :delete %>
          </div>
        </div>
      </div>
      <br>
    <% end %>
    </div>
  </div>
</div>

app/views/cards/new.html.erb
<%= form_tag("/decks/#{@deck.id}/cards/", method: :post) do %>

<%= label_tag :question, 'Question' %>
<%= text_field_tag :question  %>
<%= label_tag :answer, 'Answer' %>
<%= text_field_tag :answer  %>

<%= submit_tag 'Add Card'%>
<% end %>

app/views/cards/show.html.erb
<%= link_to "All Cards", deck_cards_path(params[:deck_id], @card.id) %>
<%= link_to "edit", edit_deck_card_path(params[:deck_id], @card.id) %>
<%= link_to "delete", deck_card_path(params[:deck_id], @card.id), :method => :delete %>


<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front" style="background-image: url(<%= FlikrFacade.new(@card.answer).word_image.flickr_url %>); background-size: 800px 800px;">
      <div class="card-text">
        <h1> <%= @card.question %> </h1>
      </div>
    </div>
    <div class="flip-card-back" style="background-image: url(<%= FlikrFacade.new(@card.answer).word_image.flickr_url %>); background-size: contain;">
      <div class="card-text">
        <h1> <%= @card.answer %> </h1>
      </div>
    </div>
  </div>
</div>

app/views/decks/edit.html.erb
<%= form_tag("/decks/#{@deck.id}", method: :patch) do %>

<%= label_tag :title, 'Title' %>
<%= text_field_tag :title, @deck.title %>
<%= label_tag :description, 'Description' %>
<%= text_field_tag :description, @deck.description %>

<%= submit_tag 'Update Deck'%>
<% end %>

app/views/decks/index.html.erb
<% if @decks.length == 1 %>
  <h1><%= "You have #{@decks.length} deck." %></h1>
<% else %>
  <h1><%= "You have #{@decks.length} decks." %></h1>
<% end  %>

<%= link_to 'Add A Deck', new_deck_path %>

<% @decks.each_with_index do |deck, index| %>
    <div class="card">
      <div class="container">
        <h2><b><%= deck.title %></b></h2>
        <p><%= deck.description %></p>
        <p><%= "#{deck.cards.length} cards" %></p>
        <%= link_to 'edit', edit_deck_path(deck.id) %>
        <%= link_to 'delete', deck_path(deck.id), :method => :delete %>
        <%= link_to 'Add A Card', new_deck_card_path(deck.id) %>
        <%= link_to 'All Cards', deck_cards_path(deck.id) %>
        <%= link_to 'Study', deck_study_index_path(deck.id) %>
      </div>
    </div>
  <br>
<% end %>

app/views/decks/new.html.erb
<%= form_tag('/decks/', method: :post) do %>

<%= label_tag :title, 'Title' %>
<%= text_field_tag :title, @deck.title %>
<%= label_tag :description, 'Description' %>
<%= text_field_tag :description, @deck.description %>

<%= submit_tag 'Add Deck'%>
<% end %>

app/views/decks/show.html.erb
<%= link_to "All Decks", decks_path %>



<div class="card">
  <div class="container">
    <h2><b><%= @deck.title %></b></h2>
    <h4><%= @deck.description %></h4>
    <%= link_to 'edit', edit_deck_path(@deck.id) %>
    <%= link_to 'delete', deck_path(@deck.id), :method => :delete %>
    <%= link_to 'Add A Card', new_deck_card_path(@deck.id) %>
    <%= link_to 'All Cards', deck_cards_path(@deck.id) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TarjetasParaEstudiar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/study/index.html.erb
<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front" style="background-image: url(<%= FlikrFacade.new(@current_card.answer).word_image.flickr_url %>); background-size: 800px 800px;">
      <div class="card-text">
        <h1> <%= @current_card.question %> </h1>
      </div>
    </div>
    <div class="flip-card-back" style="background-image: url(<%= FlikrFacade.new(@current_card.answer).word_image.flickr_url %>); background-size: contain;">
      <div class="card-text">
        <h1> <%= @current_card.answer %> </h1>
      </div>
      <%= link_to "Incorrect", deck_card_back_path(params[:deck_id], @current_card.id)%>
      <%= link_to "Correct", deck_card_flop_path(params[:deck_id], @current_card.id)%>
    </div>
  </div>
</div>

<% if @correct_count == 0 %>
  <p><%= "Let's begin!" %></p>
<% else %>
  <p><%= "You have gotten #{@correct_count} of #{@cards.length} cards correct." %></p>
<% end  %>